-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT(A.USER_ID))
FROM USER_INFO A 
    JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
HAVING GENDER IS NOT NULL 
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;
