-- 코드를 입력하세요

WITH 
temp AS 
(SELECT DISTINCT(A.CAR_ID), A.CAR_TYPE, ROUND((100 - C.DISCOUNT_RATE)*0.3*A.DAILY_FEE) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID 
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_ID NOT IN ((SELECT DISTINCT(A.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR A 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID 
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
WHERE '2022-11' BETWEEN DATE_FORMAT(B.START_DATE, '%Y-%m') AND DATE_FORMAT(B.END_DATE, '%Y-%m')
)) AND  A.CAR_TYPE IN ('세단', 'SUV')  AND C.DURATION_TYPE = '30일 이상' 
AND '2022-11' NOT BETWEEN DATE_FORMAT(B.START_DATE, '%Y-%m') AND DATE_FORMAT(B.END_DATE, '%Y-%m')
)
SELECT  *
FROM temp
WHERE 500000 <= FEE AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC

# SELECT DISTINCT(CAR_ID) AS CAR_ID, CAR_TYPE, ROUND(FEE) AS FEE
# FROM temp
# WHERE 500000 <= ROUND(FEE) AND ROUND(FEE) < 2000000 
# ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC


# CAR_ID	CAR_TYPE	FEE
# 3	세단	1518000
# 23	세단	1380000
# SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100, 0) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR A
# LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
# ON A.CAR_ID = B.CAR_ID
# LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
# ON A.CAR_TYPE = C.CAR_TYPE
# WHERE A.CAR_TYPE IN ('세단', 'SUV') 
# AND (A.CAR_ID NOT IN (
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE '2022-11' BETWEEN DATE_FORMAT(START_DATE, '%Y-%m') AND DATE_FORMAT(END_DATE, '%Y-%m')))
# AND (C.DURATION_TYPE = '30일 이상' AND (A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 2000000)
# ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;
