# -- 코드를 입력하세요

# WITH 
# final AS (WITH 
# temp AS (
# SELECT A.JOINED, B.*
# FROM USER_INFO A 
#     JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID 
# WHERE A.JOINED BETWEEN '2021-01-01' AND '2021-12-31'
# )

# # SELECT SUBSTR(SALES_DATE, 1, 4) AS YEAR, SUBSTR(SALES_DATE, 6, 2) AS MONTH, USER_ID
# # FROM temp)
          
# SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID
# FROM temp)

# SELECT YEAR, (MONTH), COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, 
# ROUND(COUNT(DISTINCT USER_ID)/COUNT(USER_ID), 1) AS PURCHASED_RATIO 
# FROM final
# GROUP BY YEAR, MONTH
# ORDER BY YEAR ASC, MONTH ASC;

SELECT DATE_FORMAT(ONLINE.sales_date, '%Y') YEAR,
       DATE_FORMAT(ONLINE.sales_date, '%m') MONTH,
       COUNT(DISTINCT ONLINE.user_id) PUCHASED_USERS,
       round(COUNT(DISTINCT ONLINE.user_id) 
             / (SELECT COUNT(user_id)
                FROM user_info
                WHERE DATE_FORMAT(joined, '%Y') = '2021'), 1) PUCHASED_RATIO
FROM user_info USERINFO JOIN online_sale ONLINE
     on (USERINFO.user_id = ONLINE.user_id) 
WHERE DATE_FORMAT(USERINFO.joined, '%Y') = '2021'
GROUP BY YEAR, MONTH