-- 코드를 입력하세요
SELECT A.WRITER_ID AS USER_ID, B.NICKNAME AS NICKNAME, SUM(PRICE) AS PRICE
FROM USED_GOODS_BOARD A 
    JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
GROUP BY A.WRITER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY PRICE ASC