# with 
# temp2 AS (with 
# temp1 AS (
# SELECT a.MEMBER_ID AS ID, a.MEMBER_NAME AS NAME, b.*
# FROM MEMBER_PROFILE a 
#     join REST_REVIEW b on a.MEMBER_ID = b.MEMBER_ID
# )
# SELECT count(REVIEW_TEXT) as cnt, ID, NAME
# FROM temp1
# GROUP BY ID
# ORDER BY cnt DESC
# )
# SELECT * FROM temp2 
# WHERE cnt = 3


# SELECT A.MEMBER_NAME,B.REVIEW_TEXT,DATE_FORMAT(B.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
# from MEMBER_PROFILE A join REST_REVIEW B
# on A.MEMBER_ID = B.MEMBER_ID
# WHERE A.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW
# GROUP BY MEMBER_ID
# ORDER BY COUNT(*) DESC LIMIT 1)
# order by REVIEW_DATE asc, REVIEW_TEXT

SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d') AS REVEIW_DATE 
FROM MEMBER_PROFILE A 
    JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    ORDER BY count(REVIEW_TEXT) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
;