SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE A 
    JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID 
WHERE B.MEMBER_ID IN
(WITH 
temp AS (SELECT A.MEMBER_ID, RANK() OVER (ORDER BY  COUNT(*)  DESC) AS RANKING
FROM MEMBER_PROFILE A 
    JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID 
GROUP BY A.MEMBER_ID 
)
SELECT MEMBER_ID 
FROM temp 
WHERE RANKING = 1)
ORDER BY B.REVIEW_DATE ASC, B.REVIEW_DATE ASC