-- 코드를 입력하세요
WITH 
temp AS 
(SELECT PRODUCT_ID, FLOOR(PRICE / 10000) *10000 AS PRICE_GROUP
FROM PRODUCT )

SELECT PRICE_GROUP, COUNT(PRODUCT_ID) 
FROM temp
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP ASC