-- 코드를 입력하세요
WITH 
temp AS 
(SELECT A.PRODUCT_ID, A.PRODUCT_NAME, (A.PRICE * B.AMOUNT) AS SALES
FROM FOOD_PRODUCT A 
    JOIN FOOD_ORDER B ON A.PRODUCT_ID = B.PRODUCT_ID 
WHERE B.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31')
SELECT PRODUCT_ID, PRODUCT_NAME, SUM(SALES) AS TOTAL_SALES 
FROM temp
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC