-- 코드를 입력하세요  DATE_FORMAT(APNT_YMD, '%Y-%m-%d')
SELECT A.APNT_NO, C.PT_NAME, C.PT_NO, A.MCDP_CD, B.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A 
    JOIN DOCTOR B ON A.MDDR_ID = B.DR_ID
    JOIN PATIENT C ON C.PT_NO = A.PT_NO
WHERE DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD ASC